build:
  image: python:3.5-onbuild
  commands:
    - apt-get update && apt-get install -y nginx
    - nginx -c $(pwd)/nginx.conf
    - python3 setup.py install
    - nosetests -v -s
    - ./uvhttp.py

