language: python
python:
- '3.5'
sudo: required
services:
- docker
script:
- make test
- pip install codacy-coverage && python-codacy-coverage -r build_results/coverage.xml
deploy:
  provider: pypi
  user: justinbarrick
  password:
    secure: MlKtZu0k7G7QcmWqrskLrpyC9SpuiZP73SuvbT9NDR/kQDK2Y+eRZoFVm3P9NYeB5PYGWMrwkRvzlHOvT5skIg9gNCO7PnQv31VNRLxHNmri/Gz+WLBFC2+xYIwc4xRIIyatPFf4t/BpX1GdL4zUV+dNGG1TNrMk3gw7WSrWPF42odw6ziecRYR88GUsigoCB89UtacMIRxSN+vHy7aaaNrLbhhLrZDQM8opG9ZORLfrszSD2YXi8z5zuCmXh2ltAl6gBPCMWaNUriXvC7vE33PpOlFp4m5wsy31MV1vuiNCXO7hOIYz32AOlIdTKMUX0MfechNTZUU40GLJUWA1xzgY3kBzWn0SCTgCXbMO8ye042An/t1wiN1A+IMZmBeVb0Ta+RWKEkCsNYT7g6TxNu/7uV6l5AMkcEjFtVuITIyazIxHbp/DSUMyjSYie6upJUZxfdz0DNAUIFrIRUohhAZRAmzNzCvhjsADEKWn1J4FK1j1xSafeYnlWVKhaYz09KU+6GyXhIzSI118IHFpNS7GwB3xD2sxjDhFkD1ukFIF/DAJbqG0LxjiQjmPLk+kRDy4EPqQkxmKpEEnLNXxV0gcC+Ft7ubc263K1BXqwnSigZWnRK7L2g4BNNE47NG0aIzHE2Y8RMn9tBkb8vTVljn7NdTamonFu3+68QXBhAM=
  on:
    branch: master
    tags: true
env:
  global:
    secure: aYXvnUqSITWiz7CZV8xFjgCsd9v3deHg6AbPHWX9C87Ez6Drdd5YMbnsXLecxohzNSvJtt965QrORVoAmpOipNtP4JPXro6UyUzWEpd4CpxXxtbJnCNjktMVfnQUNMWW+Nstpu8GJmxYKOVX6Cu1DGFERhTRUgFV801fNNFxjSSxgikK/E8Ua07Ear1U6qLkmt/tOyIt9i92PJYv/R72lxGi/q0JpkWW+TqkRjj6mUs4gaAfRVzm/IYQNFBcBEY3IkCf+DKiEPVEY28NdnZ06UB2SqDKbBysE/1lEhPr3L3h4ZVNnfHyIejw6cilbUJZ0gVD9n6FBRXWbPcDd+9t743dsn+2VUEJI++T1QNgrMFjjjJ0E6jN3Rf6vpJRMIp/VnMpNeXe74Wi9m5rWUyDwRLPaiHok04SXoIbScROZ2W9BlntBXM0/zyxky/vnSt3DdfJ8fBMQHcVHrdpPofx8jA54Aq7U/iAQk8P7ncCBwNkRWQRguCwwBUxENdp341yx4ufdYNmq/pSuHUiAo8jAGT9k6TarYdVGEK423dzM/iX5k4bNBhlzIkHYcoQacvFV7ratG/SwkFYHXn9bW51C7b/fiMGz60zSOQcddjNUdEATHYM6DJaDgHxXF2Ziplu1+xFlIF2ZItXFBfH+9e+bBYDMt5XIBIfLQPt/Kp7PKI=
