version: '2'
services:
  uvhttp:
    build:
      context: ..
      dockerfile: docker/Dockerfile

  build-docs:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: bash -c 'cd docs && make html'
    volumes:
       - ..:/uvhttp
