version: '2'
services:
  uvhttp:
    container_name: uvhttp
    hostname: uvhttp
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      uvhttp:

  build-docs:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: bash -c 'cd docs && make html'
    volumes:
       - ..:/uvhttp
    networks:
      uvhttp:

networks:
  uvhttp:
